FROM node:20.14.0-bookworm as base

WORKDIR /api

FROM base as build

COPY . /api

RUN npm install \
  && npm run build

FROM base

COPY --from=build /api/dist /api/dist

COPY --from=build /api/node_modules /api/node_modules

EXPOSE 8080

CMD ["node", "dist/src/main"]
