services:
  redis:
    image: redis:7.2.5-alpine3.19
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    networks:
      - pse_analyzer_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
  db:
    image: mysql:8.4.3-oracle
    container_name: db
    restart: always
    ports:
      - 3306:3306
    env_file: .env
    environment:
      - MySQL_TCP_PORT=3306
    volumes:
      - mysql_volume_data:/var/lib/mysql
    networks:
      - pse_analyzer_network
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    env_file: .env
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    volumes:
      - phpmyadmin_volume_data:/var/lib/mysql
    networks:
      - pse_analyzer_network
    depends_on:
      - db
  api:
    build: .
    ports:
      - 8000:8000
    env_file: .env
    container_name: api
    restart: always
    networks:
      - pse_analyzer_network
    volumes:
      - ./src:/api/src
      - /api/node_modules/
    depends_on:
      - redis
      - db
networks:
  pse_analyzer_network:
volumes:
  redis_volume_data:
  mysql_volume_data:
  phpmyadmin_volume_data:
