services:
  db:
    image: mysql:8.0.37-bookworm
    container_name: db
    restart: always
    ports:
      - 3306:3306
    env_file: .env.local
    environment:
      - MySQL_TCP_PORT=3306
    volumes:
      - mysql_volume_data:/var/lib/mysql
    networks:
      - mt_network
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin
    restart: always
    ports:
      - 8001:80
    env_file: .env.local
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - mt_network
    depends_on:
      - db
networks:
  mt_network:
volumes:
  mysql_volume_data:
