services:
  redis: 
    image: redis:7.2.5-alpine3.19
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    networks:
      - mt_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  db:
    image: mysql:8.0.37-bookworm
    container_name: db
    restart: always
    ports:
      - 3306:3306
    env_file: .env.prod
    environment:
      - MySQL_TCP_PORT=3306
    volumes:
      - mysql_volume_data:/var/lib/mysql
    networks:
      - mt_network
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin
    restart: always
    ports:
      - 8001:80
    env_file: .env.prod
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - mt_network
    depends_on:
      - db
  api:
    build: .
    ports:
      - 443:8000
    env_file: .env.prod
    container_name: api
    networks:
      - mt_network
    depends_on:
      - redis
      - db
networks:
  mt_network:
volumes:
  redis_volume_data: 
  mysql_volume_data:
